#+STARTUP: showall
#+OPTIONS: toc:nil
#+title: JAIF

* Journée thématique sur les attaques par injection de fautes

# : attaques physiques, contre-mesures, mécanismes d’évaluation de la robustesse et outlls

#+begin_export html
<p style="text-align:center; font-weight: bold;">
</p>
<p class="alert" style="text-align:center; color: #3B31D9; line-height: 2em; font-size: x-large; font-weight: bold;">
Jeudi 28 septembre 2023
<br>
Centre Microélectronique de Provence, Gardanne
<br>
</p>
<center>
</center>
#+end_export

# ** Description

Ce workshop a pour objectif de réunir la communauté de la recherche
française en analyse de fautes sur des systèmes de sécurité, pour
consolider ce savoir-faire et pour faire émerger des recherches plus
globales.  Notre communauté est très avancée sur le plan mondial, et
travaille sur des aspects variés :

+ attaques à l'aide d'injection de fautes, et modèles de fautes,
+ simulation et méthodes formelles pour évaluer la robustesse d'un
  système à une attaque par injection de fautes, et pour comprendre
  l’impact des fautes,
+ preuve de sécurité,
+ conception de contremesures matérielles ou logicielles,
+ application outillée de contremesures,
+ etc.

Le contexte des systèmes embarqués sécurisés évolue
rapidement, et il est important d’envisager l’évolution des
attaques mais aussi des systèmes.
On assiste aujourd’hui à un changement de paradigme pour aller de
systèmes fermés, tels que la carte à puce, vers des systèmes ouverts qui
embarquent des enclaves sécurisées (e.g., Trusted Execution
Environments).  Également, les attaques exploitant les injections de
fautes deviennent plus complexes, avec par exemple la possibilité de
réaliser des injections multiples ou la combinaison avec des
observations de canaux cachés.

Le [[./programme.html][programme de cette journée]] est construit de sorte à favoriser les
échanges entre les participants sur l’ensemble de ces sujets, au
travers de présentations et de discussions.


L'[[./cfp.html][appel à contributions]] est détaillé sur une page dédiée.

** Comité d'organisation

+ Vincent Beroulle  -- LCIS, Grenoble INP, Université Grenoble Alpes
+ Guillaume Bouffard --  ANSSI, ENS
+ Damien Couroussé -- CEA-List, Université Grenoble Alpes
+ Jean-Max Dutertre (local chair) -- MSE, Centre Microélectronique de Provence
+ Sylvain Guilley -- Telecom ParisTech, Secure-IC
+ Karine Heydemann -- Thales DIS France
+ Ronan Lashermes -- INRIA Rennes
+ Marie-Laure Potet -- VÉRIMAG, Grenoble INP

Contact: [[mailto:jaif@saxifrage.saclay.cea.fr][jaif@saxifrage.saclay.cea.fr]]

** Soutien institutionnel et sponsors

[[mailto:jaif@saxifrage.saclay.cea.fr][Contactez-nous]]
si vous souhaitez soutenir l'organisation de l'évènement.
