#+STARTUP: showall
#+OPTIONS: toc:nil
#+title: JAIF

* Journée thématique sur les attaques par injection de fautes

#+begin_export html
<p style="text-align:center; font-weight: bold;">
</p>
<p class="alert" style="text-align:center; color: #3B31D9; line-height: 2em; font-size: x-large; font-weight: bold;">
Jeudi 28 septembre 2023
<br>
Centre Microélectronique de Provence, Gardanne
<br>
</p>
<center>
</center>
#+end_export

L’attaque par injection de fautes est une technique souvent exploitée par les attaquants pour extraire des données confidentielles des systèmes embarqués. Ces attaques deviennent de plus en plus complexes, avec par exemple, des injections multiples ou en les combinant avec des observations de canaux cachés.

Cette journée a pour objectif de réunir la communauté académique, industrielle et étatique pour faire émerger de nouvelles collaborations, en considérant les nombreux domaines de la physique au logiciel, pour concevoir :
- Des outils d’injection de fautes, et les modèles de fautes,
- Des outils de simulation et des méthodes formelles pour évaluer la robustesse, et pour comprendre l’impact des fautes,
- Des preuves de sécurité,
- Des protections ou mécanismes de détection matériels ou logiciels,
- Des outils automatisant la conception de systèmes embarqués robustes

Le [[./programme.html][programme de cette journée]] est construit de sorte à favoriser les
échanges entre les participants sur l’ensemble de ces sujets, au
travers de présentations et de discussions.
La journée est composée d’exposés invités, de chercheurs ou d’industriels seniors, des exposés sélectionnés sur résumé, ainsi que des sessions posters sur le temps des pauses et du déjeuner.

L'[[./cfp.html][appel à contributions]] est détaillé sur une page dédiée.

** Dates importantes

- Date limite pour la [[./cfp.html][soumission de présentations ou de posters]] : le plus tôt possible avant le 23 juin
- Réponses aux auteurs : au plus tard le 15 juillet 2023
- JAIF : jeudi 28 septembre 2023

** Comité d'organisation

+ Vincent Beroulle  -- LCIS, Grenoble INP, Université Grenoble Alpes
+ Guillaume Bouffard --  ANSSI, ENS
+ Damien Couroussé -- CEA-List, Université Grenoble Alpes
+ Jean-Max Dutertre (organisateur local) -- MSE, Centre Microélectronique de Provence
+ Sylvain Guilley -- Telecom ParisTech, Secure-IC
+ Karine Heydemann -- Thales DIS France
+ Ronan Lashermes -- INRIA Rennes
+ Marie-Laure Potet -- VÉRIMAG, Grenoble INP

Contact: [[mailto:jaif@saxifrage.saclay.cea.fr][jaif@saxifrage.saclay.cea.fr]]

** Soutien institutionnel et sponsors

[[mailto:jaif@saxifrage.saclay.cea.fr][Contactez-nous]]
si vous souhaitez soutenir l'organisation de l'évènement.
