#+STARTUP: showall
#+OPTIONS: toc:nil
#+title: JAIF

# Des *navettes* et du *covoiturage* seront mis en place *entre la gare de Aix-TGV et Gardanne*.

- [2023-09-18 lun.]   Un framapad a été ouvert pour les propositions et les demandes de [[#covoiturage][co-voiturage.]]
- [2023-09-20 mer.]   Un framapad a été ouvert pour inscription à la [[#navettes][navette vers CMP / JAIF]].

** Lieu
:PROPERTIES:
:CUSTOM_ID: where
:END:

Grand Amphithéâtre, Centre Microélectronique de Provence, Mines Saint-Étienne, Campus Provence (Georges Charpak)

880, route de Mimet

F-13541 Gardanne

Transport : Bus n° 183, arrêt “Centre Charpak”

Coordonnées téléphoniques Campus de Gardanne : +33 4 42 61 66 00

Plan d’accès : [[https://www.mines-stetienne.fr/plans-dacces][Comment venir sur le Campus Provence (Georges Charpak)]]

Coordonnées GPS: 43° 26’ 44″ N / 05° 28’ 47″ E

** Navettes gare TGV Aix en Provence/Gare Gardanne – CMP
:PROPERTIES:
:CUSTOM_ID: navettes
:END:

Un car sera spécialement affrété pour les participants de JAIF.


- Matin.
   Départ à 8h00, pour une arrivée à 9h00.
   Aix gare (centre ville) -> Gardanne gare -> JAIF / CMP.
   - [[https://lite.framacalc.org/jaif2023-bus-a3c8][--> inscription sur le framapad <--]]
- Soir.  Départ à 17h10.
    JAIF / CMP -> Gare de Gardanne -> Aix TGV -> Aix gare (centre ville).
- Navette départ 19h10 (fin du social event).
    JAIF / CMP -> Gare de Gardanne -> Aix gare (centre ville)

** Covoiturage
:PROPERTIES:
:CUSTOM_ID:       covoiturage
:END:

Un document partagé est ouvert ici pour l'organisation du covoiturage :
[[https://semestriel.framapad.org/p/jaif2023-covoiturage-a2yf?lang=en][jaif2023-covoiturage-a2yf | Framapad semestriel]]

** Accès en transports en commun

*** Gardanne gare SNCF -- campus de Gardanne

Il existe des navettes régulières par la ligne 3 (Omnibus Gardanne) entre la Gare et le campus de Gardanne le matin et en fin d’après-midi.
- Réservation possible entre 9h30 et 15h45 (la veille ou au minimum 4 heures avant la course).
- Numéro vert : 0 800 00 32 35.
- En savoir plus : https://www.ville-gardanne.fr.

L’école est desservie par la ligne de bus n° 183, arrêt « Centre Charpak ».


*** Gardanne  -- Marseille

Vous pourrez y prendre aussi un bus de la ligne 64, qui permet, entre autres, de rejoindre la gare Saint-Charles, à Marseille, en 30 minutes.


*** Marseille -- Aix-en-Provence -- Aix-TGV

 [[https://www.lepilote.com/ftp/document/fiche-horaire-2022-40-fr.pdf][fiche-horaire-2022-40-fr.pdf]]


** Hotels

Nous vous recommandons de vous loger à Aix-en-Provence pour venir assister à JAIF 2023. Nous prévoyons la mise en place d’une navette et de covoiturage entre Aix et le CMP à Gardanne.



-  Appart'Hôtel Odalys City L'Atrium, 15 Cr Gambetta, 13100 Aix-en-Provence, Téléphone : 04 42 99 16 00.
-  Hôtel le Mozart, 49 Cr Gambetta, 13100 Aix-en-Provence, Téléphone : 04 42 21 62 86.


** Social Event
:PROPERTIES:
:CUSTOM_ID: social event
:END:

Le /social event/ aura lieu
de 17h30 à 19h00
au Ti'bar, bar associatif des étudiants de l'école des Mines.
Le bar est situé en face du CMP,
