:PROPERTIES:
:ID:       2023-05-16T11:40:39:vencekc1wtj0
:END:
#+STARTUP: showall
#+OPTIONS: toc:nil
#+title: JAIF 2023 -- programme

Le programme est en cours de construction.

Nous proposons aux participants de JAIF de [[./infos-pratiques.html#social event][poursuivre la journée avec un social event]] à proximité du CMP.  Détails à venir.

# *** <titre>
#
# <nom prénom> (<affiliation>)
#
# *Résumé*.
# <résumé>
#
# *Bio*.
# <bio>

# 9h40		session caracterisation 1
# talk invité		PA Moellic	20 minutes + 5 min question
# talk 1		Chancel	15 minutes + 5 min question
# talk 2		Marotta	15 minutes + 5 min question
# 10h45
# 	pause + poster
# 11h30		session analyse de programmes
#  talk 1		Gicquel	15 minutes + 5 min question
#  talk 2		Ducousso	15 minutes + 5 min question
#  talk 3		Boepflug	15 minutes + 5 min question
# 12h30
# 	dejeuner
# 14h00		Methodes et outils pour la surete et la sécurité
# talk invité		ST	20 minutes + 5 min question
# talk invité		David Hély	20 minutes + 5 min question
#  talk 1		Alexandre Iooss	15 minutes + 5 min question
# 15h05
# 	pause + poster
# 15h45		Session caracterisation et vulnerabilités
#  talk 1		DIFT Pensec	15 minutes + 5 min question
#  talk 2		Poster-Pellerin	15 minutes + 5 min question
# talk 3		Grandamme	15 minutes + 5 min question
# 16h45
# 	cloture + bye
# 17h

| 09h00 |                         | Ouverture de la salle & accueil café                                                                                                                            |
| 09h30 | Jean-Max Dutertre       | Ouverture de la journée & mot d'accueil                                                                                                                         |
| 09h40 |                         | *Session 1 -- Caractérisation et vulnérabilités #1*                                                                                                               |
|       | [[#moellic][Pierre-Alain Moëllic]]    | Injection de fautes et réseaux de neurones embarqués : intégrité et confidentialité des modèles                                                                 |
|       | [[#chancel][Geoffrey Chancel]]        | Bonnes pratiques pour l'injection de fautes par impulsions dans le substrat                                                                                     |
|       | [[#marotta][Amélie Marotta]]          | Characterizing and Modeling Clock-Glitch Fault Injection                                                                                                        |
| 10h45 |                         | Pause café - [[#posters][session posters]]                                                                                                                                    |
| 11h30 |                         | *Session 2 -- Analyse de programmes*                                                                                                                              |
|       | [[#gicquel][Antoine Gicquel]]         | SAMVA: Static Analysis for Multi-Fault Attack Paths Determination                                                                                               |
|       | [[#ducousso][Soline Ducousso]]         | Adversarial Reachability for Program-level Security Analysis                                                                                                    |
|       | [[#boespflug][Étienne Boespflug]]       | Placement of software countermeasures: a compositional approach                                                                                                 |
| 12h30 |                         | Déjeuner                                                                                                                                                        |
| 14h00 |                         | *Session 3 -- Methodes et outils pour la sûreté et la sécurité*                                                                                                   |
|       | [[#daveau][Jean-Marc Daveau]]        | Injection de fautes : Expériences dans un contexte industriels pour le durcissement de circuits                                                                 |
|       | [[#hely][David Hély]]              | Evaluation et caractérisation des attaques en fautes dès les premières étapes de la conception des circuit intégrés: outils de conception en vue de la sécurité |
|       | [[#iooss][Alexandre Iooss, Guillaume Bouffard]] | Pew Pew, I'm root! De la caractérisation à l'exploitation: un voyage plein d'embûches                                                                           |
| 15h05 |                         | Pause café - [[#posters][session posters]]                                                                                                                                    |
| 15h45 |                         | *Session 4 -- Caractérisation et vulnérabilités #2*                                                                                                               |
|       | [[#pensec][William Pensec]]          | Unveiling the Invisible Threads: Dynamic Information Flow Tracking and the Intriguing World of Fault Injection Attacks                                          |
|       | [[#postel-pellerin][Jérémie Postel-Pellerin]] | Caractérisation électrique en temps réel lors d'une attaque laser à 1064 nm sur une mémoire STT-MRAM                                                            |
|       | [[#grandamme][Paul Grandamme]]          | Injection de fautes aux Rayons X sur des composants non alimentés                                                                                               |
| 16h45 | Comité d'organisation   | Mot de clôture de la journée                                                                                                                                    |
| 17h00 |                         | Fin de la journée                                                                                                                                               |
| tbd.  |                         | [[./infos-pratiques.html#social event][social event]]                                                                                                                                                    |

** Présentations invitées

*** Injection de fautes et réseaux de neurones embarqués : intégrité et confidentialité des modèles
:PROPERTIES:
:CUSTOM_ID: moellic
:END:

*Pierre-Alain Moëllic* (CEA-Leti)

*Résumé*.
Dans un contexte de développement et de ploiement sans précédent des algorithmes d'intelligence artificielle (IA) et de tentatives de régulation de leurs usages (e.g., AI Act européen), la sécurité des systèmes d'IA est devenue une préoccupation majeure. Parmi les très nombreuses attaques visant l'intégrité, la confidentialité et la disponiblité des modèles et des données, des travaux récents ont démontrés l'importance des menaces physiques et plus particulièrement des attaques par injection de fautes. Cette présentation s'intéressera à plusieurs vecteurs d'attaque qui peuvent modifier la prédiction d'un modèle de réseau de neurones profond et ainsi altérer l'intégrité d'un système reposant sur ce type de modèle. Nous verrons que l'intégrité est loin d'être le seul objectif d'un attaquant. Les attaques dites d'"extraction de modèle" qui visent des modèles boites noires peuvent significativement tirer profit d'analyses par injection de fautes. Outre les besoins urgents de protections (réalistes), ces nouvelles attaques soulignent aussi les défis associés à l'évaluation de la robustesse de modèles de machine learning.

*Bio*.
Pierre-Alain Moëllic est ingénieur de recherche au CEA-Leti dans une équipe commune avec Mines Saint-Etienne au sein du Centre de Microélectronique de Provence (Gardannes). Il est le coordinateur du programme ANR PICTURE sur la sécurité physique et intrinsèque des réseaux de neurones embarqués et responsable du consortium Français dans le projet Européen INSECTT avec des travaux sur la sécurité de l'IA dans l'IoT. Il coordonne au sein du programme PULSE (IRT Nanoelec) la thématique de la sécurité de l'IA pour la santé à domicile.

*** Injection de fautes : Expériences dans un contexte industriels pour le durcissement de circuits
:PROPERTIES:
:CUSTOM_ID: daveau
:END:

*Jean-Marc Daveau* (STMicroelectronics)

*Résumé*.
Cette présentation aborde l'injection de fautes dans un contexte industriel pour le durcissement de circuits. Les applications incluent le durcissement d'un SERDES, d'un CPU SPARC/LEON, et la prédiction de résultats radiatifs par machine learning. L'utilisation dans le cadre de la certification ISO26262 est mentionnée. Les limites rencontrées en simulation sont évoquées ainsi que le développement d’une approche par injection de fautes formelle visant à pallier à certaines limitations de celle-ci. Les résultats préliminaires de durcissement sélectif par injection de fautes formelle sont présentés ainsi qu’une approche basée sur les modèles et la composition. Les perspectives de recherche concluent la présentation.

*Bio*.
Jean-Marc Daveau graduated from ENSI de Caen/Université de Caen in nuclear physics in 1992, TELECOM Paris in 1993 and received his PhD in Microelectronics from the Institut Polytechnique de Grenoble (INPG) in 1997. He joined STMicroelectronics in Crolles (France)  in 1999 after his post-doc at IBM TJ Watson research center in New York (USA). After working 10 years on embedded processors and DSP compilers, he currently works as a radiation testchip design engineer. His research interests include safety assessment of complex digital systems and SoCs, radiation testing and hardening of processors, reliability evaluation and fault tolerance.

*** Evaluation et caractérisation des attaques en fautes dès les premières étapes de la conception des circuit intégrés: outils de conception en vue de la sécurité
:PROPERTIES:
:CUSTOM_ID: hely
:END:

*David Hély* (LCIS, Grenoble INP-UGA)

*Résumé*.
Afin de faciliter la prise en compte des risques induits par les attaques en fautes dès les premières étapes de la conception des circuits, il est nécessaire de fournir aux concepteurs des outils permettant  d'identifier au plus tôt les éléments les plus sensibles face à ce type d'attaque. Nous aborderons dans cette présentation les enjeux liés au développement d'outil d'aide à la conception en vue de la sécurité dédié aux attaques en faute. En effet, une telle approche nécessite de développer des modèles de ces attaques à des niveaux suffisamment élevés (ici le niveau RTL), de développer des métriques  pour  quantifier les risques et de développer des outils compatibles avec les flots de conception industriels. Nous illustrerons ces éléments avec un prototype développé au LCIS.

*Bio*.
David Hély est enseignant-chercheur à Grenoble INP-UGA et effectue ses recherches au laboratoire LCIS. Il est diplômé de l’INSA Lyon et d’un doctorat de l’Université de Montpellier 2 portant sur la conception en vue du test des circuits sécurisés avec STMicroelectronics et le LIRMM. Ses thématiques de recherche concernent la conception et l’évaluation de systèmes sécurisés et le support matériel pour la sécurité des systèmes.

** Présentations

*** Bonnes pratiques pour l'injection de fautes par impulsions dans le substrat
:PROPERTIES:
:CUSTOM_ID: chancel
:END:

 *Geoffrey Chancel* (Université de Montpellier, LIRMM)

 *Résumé*.
 La présentation que nous proposons porte sur mon sujet de thèse : L’injection de fautes par impulsion dans le substrat, aussi nommée en anglais Body Biasing Injection (BBI), abréviation que nous utiliserons dans la suite de ce document.

Nous proposons de présenter les dernières avancées de nos travaux sur ce sujet, en particulier concernant les bonnes pratiques à adopter lors de la mise en place de la BBI. En effet, lors de nos études, nous nous sommes aperçus que pour accomplir des attaques par fautes grâce à cette méthode, il était nécessaire de prendre en compte de nombreux paramètres de la plateforme utilisée, comme la ligne de transmission, les interconnexions de masse entre les équipements, ou bien l’adaptation d’impédance du générateur d’impulsions. Nous proposons donc des améliorations de la pratique de la BBI. Grâce à ces dernières, nous sommes parvenus à mener une attaque par fautes sur un cœur AES 128 bits matériel, embarqué dans un microcontrôleur. L’attaque réalisée est fondée sur le modèle de faute mono bit de Giraud et al.

Enfin, nous présentons une méthode permettant de simuler et d’évaluer le comportement électrique des circuits intégrés soumis à la BBI. Pour ce faire, nous avons élaboré des modèles électriques élémentaires, qui, lorsqu’ils sont multipliés et connectés entre eux, permettent de modéliser des circuits intégrés et de comprendre les mécanismes sous-jacents impliqués dans la pratique de la BBI.

 *Bio*.
 À l’issue d’un baccalauréat scientifique, j’ai intégré l’école d’ingénieur Polytech Montpellier. Diplômé en 2020 d’un diplôme d’ingénieur en électronique et informatique industrielle, j’ai poursuivi, à la suite de mes études, un doctorat au sein du Laboratoire d’Informatique, de Robotique et de Microélectronique de Montpellier (LIRMM). Le sujet de celui-ci est l’injection de fautes par impulsion dans le substrat, plus particulièrement la modélisation et la meilleure compréhension de cette méthode.

*** Characterizing and Modeling Clock-Glitch Fault Injection
:PROPERTIES:
:CUSTOM_ID: marotta
:END:

 *Amélie Marotta* (Inria Rennes)

 *Résumé*.
 Fault injection techniques are numerous, including laser, electromagnetic fault injection (EMFI), power glitch, and clock glitch. The physical effects that are caused from fault injection result in fault models that can be interpreted at three different abstraction levels: physical (impact on logic gates and flip-flop), register-transfer (bit-set, bit-reset) and microarchitectural (impact on the execution of programs). To fully characterize the effects of fault injection, it is important to know all three abstractions levels and how they are linked to each other.

In this work, we focus on a particular type of clock glitch fault injection. We use TRAITOR, a many-fault injection platform, which uses a specific pertubation on the clock signal to induce incorrect behaviors in the target. Some observations of these behaviours at a microarchitectural level have been made, but until now, lower level fault models haven’t been proposed.

We observe that the sampling process of registers can be compromised by TRAITOR’s glitched clock. While some fault models already exist, they do not explain this behaviour. Simulation- based investigations were done to characterize precisely when a register would latch or not depending on the glitched clock cycle shape. They revealed that the issue arises due to an insufficient energy supply on the clock port of the register. Besides, experiments were done on registers in FPGAs, to highlight that the hardware environment of the target system influences the fault results.

During our presentation, we will introduce our approach to characterize the impact of TRAITOR on registers. We will present a new physical fault model which explains its effects.

 *Bio*.
 Amélie Marotta is a second-year PhD student in the TARAN team at Inria laboratory of the University of Rennes, France. Her work focuses on understanding how fault injection (electromagnetic fault injection, clock glitch) affect hardware components on FPGA (in particular, registers). She is working under the supervision of Olivier Sentieys, Ronan Lashermes, Rachid Dafali and Guillaume Bouffard.

*** SAMVA: Static Analysis for Multi-Fault Attack Paths Determination
:PROPERTIES:
:CUSTOM_ID: gicquel
:END:

*Antoine Gicquel* (Univ Rennes, Inria, CNRS, IRISA, France)

 *Résumé*.
Multi-fault injection attacks are powerful since they allow to bypass software security mechanisms of embedded devices. Assessing the vulnerability of an application while considering multiple faults with various effects is an open problem due to the size of the fault space to explore. We propose SAMVA, a framework for efficiently searching vulnerabilities of applications in presence of multiple instruction-skip faults with various widths. SAMVA relies solely on static analysis to determine attack paths in a binary code. It is configurable with the fault injection capacity of the attacker and the attacker's objective. We evaluate the proposed approach on eight PIN verification programs containing various software countermeasures. Our framework finds numerous attack paths, even for the most hardened version, in very limited time.

 *Bio*.
Antoine Gicquel is a second year Ph.D student in the PACAP team at Inria laboratory of the University of Rennes, France. His work focuses on vulnerability assessment for programs against fault injection attacks, specifically in a context of multiple faults. He is working under the supervision of Damien Hardy, Karine Heydemann and Erven Rohou.

*** Adversarial Reachability for Program-level Security Analysis
:PROPERTIES:
:CUSTOM_ID: ducousso
:END:

 *Soline Ducousso* (Université Paris-Saclay, CEA, List, Saclay, France)

 *Résumé*.
 Hardware fault injection attacks are a powerful attack vector, disturbing the execution of a program through various injection means. However, many more attack techniques yield attacker capabilities that can be seen as fault injection, ranging from software attacks to micro-architectural attacks and software-implemented hardware attacks.

 In this work, we introduce adversarial reachability, a framework allowing to reason about such advanced attackers at code level and assess program vulnerability to a particular attacker.
 Our approach is based on a new symbolic exploration algorithm, namely adversarial symbolic execution, injecting faults in a forkless manner to prevent path explosion, together with optimizations dedicated to reducing the number of injections to consider while keeping the same attacker power. Experiments on representative benchmarks from fault injection show that our method significantly reduces the number of adversarial paths to explore. In addition, we demonstrate the interest and feasibility of our technique on the well-tested WooKey bootloader.

 *Bio*.
 Soline Ducousso obtained her engineering degree from ENSTA Paris in 2020 in the fields of cybersecurity and software architecture, and a Master degree from Université Paris-Saclay the same year in theoretical computer science and formal methods. She is currently conducting her PhD at the LSL lab in the French Alternative Energies and Atomic Energy Commission (CEA), in association with VERMIAG lab in Université Grenoble Alpes. Her subject is moving code analysis from safety to security: taking the attacker into account.

*** Placement of software countermeasures: a compositional approach
:PROPERTIES:
:CUSTOM_ID: boespflug
:END:

*Étienne Boespflug* (Université de Grenoble Alpes -- VERIMAG)

 *Résumé*.
Fault attacks consist of changing the program behavior by injecting faults at runtime in order to compromise expected security properties. Multiple fault attacks enable attackers to bypass the implemented protections.
At the software level, protections primarily involve program transformations aimed at blocking or detecting attacks. We will specifically focus on countermeasures that operate at the granularity of an injection point for two LLVM-level fault models: test inversion (the ability to alter the branch taken by the program during a test) and data load mutation (changing the value during a load).
We propose a compositional approach that consists of isolation analysis and a placement algorithm. Isolation analysis aims to reason about countermeasures outside of program context, providing guarantees about the adequacy of the protection scheme against a specific fault model. It also computes the "vulnerability level", corresponding to the minimum number of faults required to produce an incorrect behavior on the protected IP with respect to a set of fault models (determining the attack surface of the countermeasures).
Five placement algorithms are presented, relying on the vulnerability level and an exploration of attack paths in the program to produce a protected program. Each algorithm shows different complexity and robustness guarantees.

 *Bio*.
Etienne Boespflug is currently a post-doctoral researcher at VERIMAG. He completed a master’s degree in computer science and security at the University of Limoges and defended his thesis prepared at VERIMAG entitled "Tools for code and countermeasures analysis against multiple faults attacks" on 28/04/23.

*** Pew Pew, I'm root! De la caractérisation à l'exploitation: un voyage plein d'embûches
:PROPERTIES:
:CUSTOM_ID: iooss
:END:

*Alexandre Iooss* (ANSSI -- Laboratoire Sécurité des Composants),
*Guillaume Bouffard* (ANSSI -- Laboratoire Architectures Matérielles et Logicielles)

 *Résumé*.
Les attaques par injections de fautes (FI) ne sont généralement pas considérées dans les modèles de sécurité des systèmes embarqués complexes. Cependant, elles constituent une menace pour la sécurité globale du système si un attaquant parvient à identifier et à reproduire une vulnérabilité par FI. La réussite de telles attaques implique cependant trois étapes : caractériser les effets d'une FI, modéliser les chemins d'attaque possibles par rapport aux effets des FI et exploiter l'impact des FI. Alors que les travaux antérieurs se sont principalement concentrés sur la sécurité des implémentations cryptographiques sur les microcontrôleurs, le développement d'appareils mobiles, tels que les smartphones, étend la menace d'attaques semi-invasives à un plus large éventail d'applications. Pour protéger efficacement ces systèmes, il est nécessaire de disposer d'une méthodologie permettant d'évaluer les conséquences au niveau du comportement du logiciel en cas de FI.

Dans cette présentation, nous décrivons comment transposer un modèle de faute obtenu depuis le jeu d'instruction sur un logiciel complexe, avec des bibliothèques partagées. Dans ce travail, nous nous focalisons sur la sécurité de l'application sudo packagée dans la distribution GNU/Linux Raspberry Pi OS pour Raspberry Pi 4. Dans cette présentation, nous démontrons comment la caractérisation de sensibilité FI peut être utilisée pour trouver des faiblesses dans des logiciels complexes et, qu'en l'absence de protections, une attaque peut effectivement réussir. Nous montrons que nous pouvons forcer l'authentification sans modifier le binaire cible de sudo.

*Bios*.

Alexandre Iooss est ingénieur de recherche à l'ANSSI à Rennes.
Ses travaux portent sur le développement d'outils d'analyse de la sécurité matérielle. Il
développe des simulateurs de canaux auxiliaires et d'injections de fautes. Il se passionne
également pour le développement de logiciels libres.

Guillaume Bouffard est chercheur en securité des implémentations logicielles embarquées à l'ANSSI à Paris.
Ses travaux portent sur la sécurité des implémentations de la racine de confiance. Il se
focalise principalement sur les problématiques de sécurité du logiciel embarqué aux interfaces
logicielles/matérielles.

*** Unveiling the Invisible Threads: Dynamic Information Flow Tracking and the Intriguing World of Fault Injection Attacks
:PROPERTIES:
:CUSTOM_ID: pensec
:END:

*William Pensec* (UMR 6285, Lab-STICC, Université Bretagne Sud)

 *Résumé*.
L'internet des objets (IoT) manipulent des données sensibles, ce qui entraîne des besoins de sécurité fiables. Ils sont confrontés à des attaques logicielles et physiques en raison de leur connectivité réseau et de leur proximité avec les attaquants. Ces appareils sont généralement construits autour de processeurs à faible coût et à faible puissance. Dans ce travail, nous étudions l'impact des attaques par injection de fautes (FIA) sur le processeur D-RI5CY intégrant un mécanisme de suivi dynamique du flux d'informations (DIFT) contre les attaques logicielles. Nos résultats mettent en évidence la grande sensibilité de la cible à de multiples types de fautes à de multiples emplacements spatiaux et temporels.

 *Bio*.
William Pensec a obtenu son Master en Informatique avec une spécialisation en logiciels pour les systèmes embarqués à l'Université de Bretagne Occidentale (UBO), à Brest, en 2021. Il a rejoint l'équipe ARCAD au sein du laboratoire Lab-STICC en France et a commencé son doctorat en 2021 dans le domaine de la sécurité matérielle à l'Université Bretagne Sud à Lorient. Ses recherches portent sur la sécurité des systèmes embarqués, RISC-V, les attaques par injection de fautes, dans le but de protéger un cœur RISC-V contre les attaques logicielles et physiques.

*** Caractérisation électrique en temps réel lors d'une attaque laser à 1064 nm sur une mémoire STT-MRAM
:PROPERTIES:
:CUSTOM_ID: postel-pellerin
:END:

 *Jérémy Postel-Pellerin* (Aix Marseille University, CNRS, IM2NP, Marseille, France)

 *Résumé*.
 Le projet MISTRAL, coordonné par Mines Saint-Etienne à Gardanne, en collaboration avec le CEA, Spintec et l'IM2NP est financé par l'Agence Nationale de la Recherche (projet ANR- 19-CE39-0010) dans le but de sécuriser des algorithmes de cryptographie légère par hybridation CMOS/STT-MRAM.

En effet, le domaine de la microélectronique est fortement stimulé par l'avènement de l'Internet des objets (IoT) et les objets connectés doivent être bon marché et très peu consommateurs en énergie, mais aussi très fiables et sécurisés. Néanmoins, la sécurité est bien connue pour avoir un coût en termes de consommation d'énergie et de surface de silicium. Ainsi, la cryptographie dite "légère" (ou LightWeight Cryptography-LWC) devrait alors jouer un rôle majeur pour le développement de l'IoT. Ces algorithmes doivent être implantés de manière sécurisée afin de faire face aux attaques physiques (analyse par canaux auxiliaires ou attaques basées sur les perturbations), mais les contre-mesures proposées sont consommatrices en énergie. Ainsi, en raison de ses faibles besoins en énergie, il devient possible d'hybrider des mémoires STT-MRAM avec le CMOS, puis de construire une logique non-volatile (NV), pour les objets connectés qui doivent se réveiller sur un événement et conserver le stockage des données lorsque le circuit est sporadiquement éteint.

Dans ce contexte, cette présentation se focalise sur le développement d'un banc mixte mêlant injection laser et caractérisation électrique dynamique, ainsi que sur l'effet de ce laser sur la cellule STT-MRAM. Nous présentons la variation du courant de la cellule pendant l’illumination laser dans une condition de lecture pour différentes puissances du laser. L'établissement d'un courant excessif ou insuffisant, selon le signe de la tension de lecture, peut avoir un impact sur les circuits de détection utilisés pour lire la cellule, ou dans une configuration de circuit hybride. Pour comprendre en profondeur le comportement de la cellule, nous avons vérifié qu'il est possible d'obtenir une commutation de la cellule d'un état pour lequel les aimantations des deux couches ferromagnétiques de la Jonction Tunnel Magnétique sont en configuration Anti-Parallèle (état AP de forte résistivité) à un état en configuration Parallèle (état P de faible résistivité) sans dégradation. La tension de lecture, la durée d’injection, ainsi que la taille de la cellule, ont un impact sur la probabilité de commutation et doivent être pris en compte pour développer un mécanisme de protection. Enfin, nous démontrons la corrélation directe entre la puissance du laser et la température pendant la phase de programmation, montrant la réduction de la fenêtre de programmation en fonction de ces deux aspects physiques. Il est donc possible d'émuler une attaque au laser en tenant compte des variations du modèle électrique dans une large plage de température. Enfin, le modèle associé à ces injections laser sur les STT-MRAM sera utilisé pour la conception par hybridation STT-MRAM/CMOS du circuit de cryptographie légère ASCON.

 *Bio*.
 Né en 1982, Jérémy Postel-Pellerin a obtenu son diplôme d'ingénieur et son doctorat de l'Université d'Aix-Marseille en 2005 et 2008 respectivement. Il a rejoint l'équipe Mémoires de l'Institut Matériaux Microélectronique Nanosciences de Provence (IM2NP), à Marseille, en France, en 2009, et est devenu maître de conférences à l'Université d'Aix-Marseille. Ses domaines de recherche actuels comprennent la caractérisation électrique, la modélisation et la simulation TCAD des mémoires, notamment pour des études de fiabilité et de sécurité.

*** Injection de fautes aux Rayons X sur des composants non alimentés
:PROPERTIES:
:CUSTOM_ID: grandamme
:END:

 *Paul Grandamme* (Laboratoire Hubert Curien - Université Jean Monnet de Saint-Éteinne, Mines Saint-Étienne)

 *Résumé*.
 Depuis de nombreuses années, les composants électroniques ont pris une place de plus en plus importante dans nos vies. Leur sécurité est devenue un enjeu crucial car ils peuvent contenir des informations sensibles. Pour s’assurer de leur sécurité de nouveaux moyens d’injection de fautes ont été mis en place. Les effets des rayons X sur les circuits électroniques sont étudiés depuis quelques décennies mais seulement quelques travaux ont été menés sur l’aspect sécuritaire. L’état de l’art nous montre que les rayons X peuvent avoir un effet sur les circuits non alimentés contrairement aux autres moyens d’injection de faute (électromagnétique, laser).

Cette étude fournit des résultats expérimentaux d’injections de fautes aux rayons X sur des microcontrolleurs non alimentés en énergie. On s’intéresse notamment aux mémoires non-volatiles embarquées dans les microcontrolleurs. Cette présentation montre qu’il est possible de corrompre le contenu d’une mémoire non alimentée. De plus, un modèle de faute en accord avec les résultats expérimentaux est aussi proposé. Enfin, il est aussi montré qu’une récupération thermique est aussi possible après injection.

 *Bio*.
 Paul Grandamme est doctorant au laboratoire Hubert Curien de l’Université Jean Monnet de Saint-Étienne. Après des études à l’École des Mines de Saint-Étienne (EMSE) au sein du cursus ISMIN (Ingénieur Spécialisé Microélectronique et INformatique) orienté sur la conception en microélectronique, il effectue son stage de fin d’étude dans le département Systèmes et Architectures Sécurisés (SAS) de l’EMSE sur l’analyse Side-Channel des communications par fibre optique. Il réalise actuellement sa thèse sur l’étude des attaques par injection de fautes sur des circuits non alimentés dans le cadre du projet ANR POP.

** Sessions posters
:PROPERTIES:
:CUSTOM_ID: posters
:END:

|   | Vincent Beroulle        | Experimental Evaluation of Delayed-based Detectors against Power-off Attack                                            |
|   | [[#chancel][Geoffrey Chancel]]        | Bonnes pratiques pour l'injection de fautes par impulsions dans le substrat                                            |
|   | [[#pensec][William Pensec]]          | Unveiling the Invisible Threads: Dynamic Information Flow Tracking and the Intriguing World of Fault Injection Attacks |
|   | [[#postel-pellerin][Jérémie Postel-Pellerin]] | Caractérisation électrique en temps réel lors d'une attaque laser à 1064 nm sur une mémoire STT-MRAM                   |
|   | Souhir Mhira            | Secure Manager                                                                                                         |
|   | Pierre-Antoine Tissot   | BALoo: First and Efficient Countermeasure dedicated to Persistent Fault Attacks                                        |
|   | Hongwei Zhao            | Fault attack on the communication architecture of a RISC-V based system                                                |
